# workflow name
name: Unit Tests

# execute on events
on:
  [push]

# jobs to run
jobs:
  
  # install dependencies and run test command
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # 3: Cache dependencies
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
          
      # 4: install NPM dependencies
      - name: Install dependencies
        run: npm install
      
      # 5: run test command
      - name: Run test command
        run: npm run test
